services:
  - type: web
    name: job-logger-api
    env: python
    region: oregon
    plan: free
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: NEON_DB_URL
        sync: false
